### PR TITLE
for-loop tests and fixes

### PR DESCRIPTION
**Pull request by mshinwell**
Compilation of `for`-loops is currently broken; when the bound for an increasing loop is `max_int` then we add one to it causing overflow.  Likewise in the other direction.  There is a test case here that we should upstream.

### CODE REVIEW

**Comment by mshinwell** [comment]
I also checked the evaluation order as per the existing CR.  I think the new code matches `Cmmgen` in this regard (the starting bound is evaluated before the finishing bound).

**Comment by lthls** [comment]
Is there a reason not to produce the same tests as closure and flambda1 ?
For a program like this:
```ocaml
for i = 0 to 2 do
  something ()
done
```

they both produce
```
(let i 1
  (catch
    (if (> i 5) (exit 1)
      (catch rec (exit 2) with(2)
        (<loop code>)
        (let i/1 i (assign i (+ i 2))
          (if (== i/1 5) (exit 1) []))
        (exit 2)))
  with(1) []))
```

while this PR produces
```
(catch
  (if (<= i 5)
    (catch rec (exit 2 1) with(2 i: val)
      (<loop code>)
      (if (< i 5) (exit 2 (+ i 2)) (exit 1)))
    (exit 1)))
with(1) 1))
```

The first test is inverted, and the second one is an inequality instead of an equality (and is inverted too)

**Comment by mshinwell** [comment]
@lthls Can you paste the assembly output for those two?

**Comment by lthls** [comment]
The first one:
```
.L103:
        movl    $1, %ebx
        cmpq    $5, %rbx
        jg      .L101
        movq    %rbx, 8(%rsp)
        movq    %rax, (%rsp)
.L102:
        movl    $1, %eax
        movq    (%rsp), %rbx
        movq    (%rbx), %rdi
        call    *%rdi
.L100:
        movq    8(%rsp), %rbx
        movq    %rbx, %rax
        addq    $2, %rbx
        movq    %rbx, 8(%rsp)
        cmpq    $5, %rax
        jne     .L102
.L101:
        movl    $1, %eax
```

This PR:
```
.L103:
        movq    %rax, (%rsp)
        movl    $1, %eax
        movq    %rax, 8(%rsp)
.L101:
        movq    (%rsp), %rbx
        movl    $1, %eax
        movq    (%rbx), %rdi
        call    *%rdi
.L100:
        movq    8(%rsp), %rax
        cmpq    $5, %rax
        jge     .L102
        addq    $2, %rax
        movq    %rax, 8(%rsp)
        jmp     .L101
        .align  4
.L102:
        movl    $1, %eax
```

**Comment by lthls** [comment]
Something seems wrong with the output for this PR, as I don't see the initial test

**Comment by lthls** [comment]
Never mind, it has been removed as it was trivially true

**Comment by mshinwell** [comment]
@lthls Hmm, the first of these does look more like a normal loop, which might be better for the CPU.  Do you want to try to adjust this PR to produce that?  I think leaving the first test is ok though.

**Comment by lthls** [comment]
I've made a PR. If I use an equality instead of a disequality (like closure and flambda1), the generated assembly looks slightly worse, but I've only looked at very small examples so I'm not sure which one is better in the general case.
I think `Linearize` inverts tests when it can generate better code, so for the first test it should not matter at all.

**Pull request merged**
