### PR TITLE
Fix bug in unboxing decision code + use max unboxing depth cli flag

### PR DESCRIPTION
**Pull request by Gbury**

### CODE REVIEW

**Comment by Gbury** [comment]
So, in this case, CI found a bug with the new implementation of unboxing (this PR triggers it because it makes the default max unboxing depth go from 1 to 3). I think I see what the bug is, I'm working on fixing it.

**Comment by Gbury** [comment]
This PR now also fixes a bug in the unboxing code, see the commit message.

**Comment by mshinwell** [comment]
@Gbury Please can you discuss the typing env changes with @lthls and also have @chambart approve the unboxing-related changes.

It looks like some of the meet tests have been accidentally commented out in this diff?

**Comment by Gbury** [comment]
Sure, though in practice, except for the invariant code for aliases, all of the typing_env change actually come from one of the commits of @lthls in #316 
The commented out tests are indeed an error.

**Comment by lthls** [comment]
The typing env changes are correct, and @gbury and @chambart explained to me why the new unboxing code triggers a bug that needs this patch (at the time I wrote the patch, I wasn't sure how to actually trigger the bug, so I left it in the draft PR and forgot about it).

**Comment by Gbury** [comment]
This has been rebased, so it should be good for merging once CI is green.

**Pull request merged**
