### PR TITLE
Improvements to the typing operations

### PR DESCRIPTION
**Pull request by lthls**
- Split meet and join systematically
- Make `meet` functions return `t Or_bottom.t` and `join functions return `t Or_unknown.t` systematically
- Rewrite Typing_env_extension. Now it doesn't depend on Typing_env_level anymore, and is split into three modules:
  - Typing_env_extension for extensions coming from meet operations
  - Typing_env_extensions.With_cse for extensions coming from simplification
  - Typing_env_extension.With_extra_variables for make_suiteable_for_environment (and potentially join in general)

Things left to do:
- Cleanup (remove commented code, or un-comment it but prefix the function name with `_` if it's worth keeping)

### CODE REVIEW

**Comment by Gbury** [comment]
Just for some context, is this PR aimed at code organization and cleanliness, soundness or compilation speed (or a combination of all three) ?

**Comment by lthls** [comment]
Mostly soundness and ease of reasoning about it (so that's code organisation and cleanliness too, I guess).

**Comment by lthls** [comment]
I've actually included #281 here by accident (I needed it to build some opam packages, so I cherry-picked it, and I forgot about it when I pushed). I can remove it for ease of review, if necessary, but I could also merge it and rebase, which will have the same effect.

**Comment by Gbury** [comment]
+1 for merging and rebase, ^^ (we should probably merge a few of the currently pending PR to avoid too much of a backlog or these kind of problems I think).

**Comment by lthls** [comment]
I've edited the description of this PR with the things I would still like to do.
The cleanup and renaming are both not very hard and not very important, but I'd like to look at the issue of `Unknown` in join a bit more.

**Comment by lthls** [comment]
I've done the `Meet_or_join_env` -> `Join_env` renaming, and made a few tweaks to the `join` types that fix the issue of unhandled `Unknown` cases.
When CI goes green I'll edit the description to reflect this.

**Pull request merged**
