### PR TITLE
Allow a Rec_info.t to have infinite depth

### PR DESCRIPTION
**Pull request by lukemaurer**
This will be used to assume that an unknown depth is infinite.

### CODE REVIEW

**Comment by lpw25** [comment]
I'm not sure that you really want this in `Rec_info.t`. Although I'm also not entirely sure what `Rec_info.t` is for, as opposed to the more general "rec info term language" type that allows depth variables etc, which might mean that I'm misunderstanding the intention here.

**Comment by lpw25** [comment]
More concretely: "Where are you expecting `Rec_info.t` to appear in the system? Do those places need an infinity value?"

**Comment by lukemaurer** [comment]
It's what a free depth parameter will evaluate to as a depth expression. `Inlining_decision` will see this as meaning it's definitely deeper than the max recursion depth, so we should stop (unless it's `[@unrolled]`).

Granted, this ties pretty deeply into the logic of `Inlining_decision`, but that's also true of the `unroll_to` field of `Rec_info.t`, which really can't be described without going into how `[@unrolled]` works.

**Comment by lpw25** [comment]
I guess was expecting to have a single funtion:

```ocaml
val depth_is_less_than : Rec_info_expr.t -> int -> bool
```
rather than a separate type `Rec_info.t` and functions:
```ocaml
val evaluate : Rec_info_expr.t -> Rec_info.t
val is_depth_less_than : Rec_info.t -> int -> bool
```

**Comment by lukemaurer** [comment]
That would make sense. There are two things we want to project out, though: the recursion depth and the unrolling state. And we'd want to avoid reevaluating the expression (though that's probably never going to take long).

**Comment by lpw25** [comment]
I think that you could get away with:
```ocaml
val simplify : Rec_info_expr.t ->Rec_info_expr.t
```
to avoid repeated work. As long as the normal forms are all succinct that would be fine (e.g. `Incr(3, Var n)` rather than `Succ(Succ(Succ(Var n)))`).

Having the `Rec_info.t` just for the time between simplifying and checking the properties seems fine too though.

**Comment by lukemaurer** [comment]
Closing. This has been folded into #452.

**Pull request closed without merging**
