### PR TITLE
Compute size during closure conversion

### PR DESCRIPTION
**Pull request by poechsel**
Code fragments were storing instances of [Cost_metrics.t Or_unknown.t]. We thought we could go with it and that 
missing cost metrics would be fully recovered during simplifications but that's not the case for set of closures
where we have a bootstrapping problem and where all cost metrics should be known before being able
to simplify one closure. This PR removes the need for [Or_unknown.t] and computes the cost metrics
during closure conversion.
This was also the occasion to refactor closure conversion and remove all mutable states from it by adding an
[Acc.t] that is pipe through the conversion.

I added an assert to check that the size computed during closure conversion is indeed the correct size. This assert is only triggered when COST_METRICS is set in the env.

### CODE REVIEW

**Comment by mshinwell** [comment]
One comment: I'd rather not use the word "wrapper" for the extra modules in `Closure_conversion`.  We usually reserve that word to mean a worker-wrapper setup, e.g. for removing parameters from a function, or some extra code around a continuation.

**Comment by poechsel** [comment]
What would you suggest as an alternative? Replacing [wrapper] with [_with_acc] ?

**Comment by mshinwell** [comment]
Yeah, that sounds ok.

**Comment by mshinwell** [comment]
This is OK to merge once my changeset of minor fixes gets through CI.

The one thing that is strange, which we should probably fix in a follow-up PR, is that code size now has to be specified in the fexpr language used for tests etc (as far as I can tell).  I wonder if instead the code size should be computed directly whilst converting fexpr to Flambda.  This is a similar situation to #378.  There, we would ideally have the free names computations for expressions available.  I think we should maybe establish a library of utility functions, such as size and free name computations, which can live outside of the main Flambda system but be used for testing.  Their review requirements can then be lower.

cc @lukemaurer

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
