### PR TITLE
Add script to build flambda2

### PR DESCRIPTION
**Pull request by Gbury**
This PR adds a script to help in building the flambda2 compiler, the flambda2 stdlib, and use these.

In  order to work, a user needs to fill in paths to 4 distinct compiler clones/worktrees that will be used:
- a first stage, used to build the flambda2 compiler
- a second stage, whose compiler will be overriden with the flambda2 compiler
- a flambda2 dev branch, where changes can be made and tested
- a final repo, which will be used to compile the stdlib (and the regular compiler) using the second stage compiler (which has been overridden with the flambda2 compiler)

The script is able to: clean, configure and build all 4 stages, as well as invoke the flambda2 compiler with or without the flambda2 stdlib. Refer to `./flambda2.sh help` for more information about the commands.

The added script is deliberately added to the .gitignore so that users can fill in the 4 variables to point at their respective git clones/worktrees without worrying about accidentally commiting them.

### CODE REVIEW

**Comment by mshinwell** [comment]
I will review this, thanks.

**Comment by Gbury** [comment]
ping on that review ?

**Comment by Gbury** [comment]
I pushed an update to the script, so that we can actually run the testsuite (or at least part of: only ocamlopt.opt is really tested with the current setup).

For ocamltest to run, the repo pointed at by the `FIRST_STAGE` variable of the script should be checked out with the `hack_ocamltest` branch of the flambda repository.

On my machine the results of the testsuite are actually better than I expected (there is one test ('testarg.ml') which I had to kill manually in order for the testsuite to terminate):
```
Summary:
  1157 tests passed
   32 tests skipped
  756 tests failed
  462 tests not started (parent test skipped or failed)
    0 unexpected errors
  2407 tests considered

**Comment by Gbury** [comment]
Not relevant anymore since the makefile build works now.

**Pull request closed without merging**
