### PR TITLE
Refactor inlining depth to its own module.

### PR DESCRIPTION
**Pull request by poechsel**
This PR adds a new module, `Inlining_state` that represents the data needed to track the current state of inlining. For now `Inlining_state` is only composed of `depth` (the current inlining depth) but in the near future it will also contain other things, like the inlining parameters used to compile the file.

### CODE REVIEW

**Review by lukemaurer — COMMENTED** [review]
Looks good to me.

**Comment by poechsel** [comment]
Thanks!

@mshinwell do you have anything to add?

**Comment by mshinwell** [comment]
Yeah, when adding a new `.mli` file, please add a comment (after the initial licensing comment) that gives a brief description of what the file is for.  This applies to `Inlining_state` in this PR.

Also in `inlining_state.mli`, I would suggest reordering the functions, since they're in a kind of random order for reading at the moment.  I tend to start with `type t`, then printing, creation and other functions after that.

**Comment by poechsel** [comment]
Rebased everything

**Comment by mshinwell** [comment]
@poechsel The contents of the most recent changeset don't match the commit message (which only mentions reordering functions in the `.mli`).  Can you confirm the other changes are intended to be there?

**Comment by poechsel** [comment]
The changes are intended to be there. I'll split the commit in two to make it more explicit.

**Pull request merged**
