### PR TITLE
Add Compare module and flexpect tool

### PR DESCRIPTION
**Pull request by lukemaurer**
New syntax and updated parser for Flambda 2.0 source, as well as support for doing equality comparison on Flambda 2.0 (mostly untested so far).

### CODE REVIEW

**Comment by mshinwell** [comment]
Could you try to split out some of the individual pieces into separate PRs?  Two that immediately come to mind are the change for closure bindings; and the `pattern_match_pair` function.

**Comment by lukemaurer** [comment]
> Could you try to split out some of the individual pieces into separate PRs? Two that immediately come to mind are the change for closure bindings; and the `pattern_match_pair` function.

Sure.  How should I handle the dependencies between the PRs?

**Comment by mshinwell** [comment]
Unfortunately there's no good solution for the dependencies.  One approach is to reduce each PR to a single changeset, which means it's easy to cherry-pick the commits forward into the PRs that depend on it.

**Comment by mshinwell** [comment]
Also, we can get these things reviewed quickly, so you shouldn't be in a state for long where there are lots of PRs stacked on top of each other.

**Comment by lukemaurer** [comment]
Okay, I split things off into #185 (already merged) and #189.

**Comment by lukemaurer** [comment]
Marking as draft since this now depends on #227 and #210.

**Comment by lukemaurer** [comment]
Re-titling this since the purpose of the branch has morphed over time.  Also note that it now depends on #228 in addition to #210 and #227.

**Review by mshinwell — APPROVED** [review]

**Pull request merged**
