### PR TITLE
Fix merge functions in patricia trees

### PR DESCRIPTION
**Pull request by Gbury**
This patch fixes and un-comments the merge function on patricia trees as maps. The main bug that was there was that the old code did not recurse on the trees enough and thus it did not call the user-provided `f` function on some keys and bindings of the map.

I was looking at fixing all of the functions that are missing an implementation, but stumbled onto the problem that given the structure of patricia trees, we do not have access to the elements/bindings of a set/map in the expected order for integers. This is the case at least in part because the implementation chooses to discriminate on the least significant bit that differs (which is what I assume the "little endian" comment at the beginning of the file refers to), and thus the order of branches is relatively unrelated to the usual ordering on integers. Thus comes two questions:
- should the functions provided by the patricia tree adhere to the documentation of their `Map` counterpart, most notably concerning ordering (i.e. fold that calls the function on increasing elements), etc.. and if so is the "natural" ordering on integers the one that must be respected ? or is any ordering fine ? I'd guess that currently any ordering is fine since there are already functions such as fold which are not called on naturally increasing keys.
- If we need to mimic the natural ordering on integers for at least some functions, am I wrong in thinking that changing the implementation to a big-endian (i.e. discriminating on the highest differing bit instead of the lowest) would make it so that the trees are in the natural order for unsigned integers ?
cc @mshinwell

### CODE REVIEW

**Comment by Gbury** [comment]
Also, it might be useful later to be able to write some quick-check style tests to check the patricia tree implementation (by comparing it to the regular Maps in the compilers), though it would be a bit complicated due to the deps I expect. Is that something that could be somehow done in the shiny flambda-backend repo maybe (I suspect using dune would help a lot in a scenario where we try and vendor quickcheck and build it with the fresh compiler before running the testsuite) ?

**Comment by mshinwell** [comment]
As far as I recall swapping the endianness will indeed mean that the ordering coincides, but I will have to remind myself of the details.  It would certainly be nice if we could make the interface compatible with the standard library in terms of the traversal order.  Agreed that we should try some kind of quick-check style thing, that probably will be easier in the Flambda backend repo.

**Comment by Gbury** [comment]
@mshinwell ping ? I think we can merge this PR and wait later to see if we want to swap the endianness in order to implement the currently not-implemented functions.

**Comment by mshinwell** [comment]
I've added a CR comment about endianness.

**Pull request merged**
